# Generated by Django 4.2.7 on 2024-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=None, verbose_name='Опубликована ли книга'),
        ),
    ]
