# Generated by Django 4.2.7 on 2024-01-29 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_book_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='лайк')),
                ('in_bookmarks', models.BooleanField(default=False, verbose_name='закладки')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'Good'), (3, 'Super'), (4, 'Amazing'), (5, 'Incredible')], verbose_name='рейтинг')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.book', verbose_name='книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
