# Generated by Django 4.2.7 on 2024-01-29 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_userbookrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(related_name='books_reactions', through='store.UserBookRelationship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец книги'),
        ),
        migrations.AlterField(
            model_name='userbookrelationship',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='store.book', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='userbookrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
