# Generated by Django 4.2.7 on 2024-01-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_reader_alter_book_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelationship',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'Good'), (3, 'Super'), (4, 'Amazing'), (5, 'Incredible')], null=True, verbose_name='рейтинг'),
        ),
    ]
