# Generated by Django 4.2.7 on 2024-02-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_reating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reating',
            new_name='rating',
        ),
    ]
